# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml"
loaderVersion="[35,)"
license="GPL-3.0 License"
issueTrackerURL="https://github.com/grim3212/AssortedStorage"

[[mods]]
modId="assortedstorage"
version="${file.jarVersion}"
displayName="Assorted Storage"
#updateJSONURL=""
displayURL="https://grim3212.com/"
logoFile="logo.png"
authors="Grim3212"
description='''
Assorted blocks and items useful for storage
'''

[[dependencies.assortedstorage]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.assortedstorage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
